apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      initContainers:
      - name: install-packages
        image: python:3.8-slim-buster
        command: ['pip', 'install', 'Flask==2.2.2', 'Werkzeug==2.2.2']
        volumeMounts:
        - name: shared-libs
          mountPath: /usr/local/lib/python3.8/site-packages
      containers:
      - image: fjacinto349/images:app-1
        name: flaskdemo
        resources: {}
        ports:
        - containerPort: 5000
      volumes:
      - name: shared-libs
        emptyDir: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
